import os
import csv

folder_path = "final_data"

###### Iterate through the folders: test, train, and valid
for folder_name in ["test", "train", "valid"]:
    folder_dir = os.path.join(folder_path, folder_name)

    # Iterate through the files in the current folder
    for file_name in os.listdir(folder_dir):
        file_path = os.path.join(folder_dir, file_name)

        # Check if the file is a text file
        if file_name.endswith(".txt"):
            csv_file_path = os.path.splitext(file_path)[0] + ".csv"

            # Open the input and output files
            with open(file_path, "r") as input_file, open(csv_file_path, "w", newline="") as output_file:
                tsv_reader = csv.reader(input_file, delimiter="\t")
                csv_writer = csv.writer(output_file)

                # Write the data to the CSV file
                csv_writer.writerows(tsv_reader)
                
            # Remove the original text file
            os.remove(file_path)

In [91]:
import os
import pandas as pd
from tqdm import tqdm

In [112]:
filepath = os.path.join('data', 'ES2002a.csv')
filepath

'data\\ES2002a.csv'

In [50]:
df = pd.read_csv(filepath, header=None, names=["Speaker_Name", "Start_time", "Content", "Intent"])
df

In [61]:
df = df.drop(['Start_time'], axis=1)
df = df.drop(['Intent'], axis=1)
df

    Speaker_Name                                            Content
0              A                                      Hmm hmm hmm .
1              B  Are we we're not allowed to dim the lights so ...
2              A                                             Yeah .
3              B                               Okay , that's fine .
4              B            Am I supposed to be standing up there ?
..           ...                                                ...
283            B                     So , see you in half an hour .
284            D                        Do we go back to our room ?
285            B                                I think so , yeah .
286            A                                        Mm , yeah .
287            D                                              Yep ?

[288 rows x 2 columns]

In [66]:
str0 = df['Speaker_Name'][0]+': '+df['Content'][0]
str0

'A: Hmm hmm hmm .'

In [67]:
str1 = df['Speaker_Name'][1]+': '+df['Content'][1]
str1

"B: Are we we're not allowed to dim the lights so people can see that a bit better ?"

In [76]:
srt = str0 + '\n' + str1

In [73]:
from datasets import load_dataset

dataset = load_dataset("samsum")

Downloading and preparing dataset samsum/samsum to C:/Users/harde/.cache/huggingface/datasets/samsum/samsum/0.0.0/f1d7c6b7353e6de335d444e424dc002ef70d1277109031327bc9cc6af5d3d46e...

Downloading data:   0%|          | 0.00/2.94M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/14732 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/819 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/818 [00:00<?, ? examples/s]

Dataset samsum downloaded and prepared to C:/Users/harde/.cache/huggingface/datasets/samsum/samsum/0.0.0/f1d7c6b7353e6de335d444e424dc002ef70d1277109031327bc9cc6af5d3d46e. Subsequent calls will reuse this data.

  0%|          | 0/3 [00:00<?, ?it/s]

In [75]:
print(dataset['test'][0]["dialogue"])

Hannah: Hey, do you have Betty's number?
Amanda: Lemme check
Hannah: <file_gif>
Amanda: Sorry, can't find it.
Amanda: Ask Larry
Amanda: He called her last time we were at the park together
Hannah: I don't know him well
Hannah: <file_gif>
Amanda: Don't be shy, he's very nice
Hannah: If you say so..
Hannah: I'd rather you texted him
Amanda: Just text him 🙂
Hannah: Urgh.. Alright
Hannah: Bye
Amanda: Bye bye

In [93]:
#%%time

for row in tqdm(df.itertuples()):
    row

288it [00:00, ?it/s]

In [81]:
df_dict = df.to_dict('records')
df_dict

[{'Speaker_Name': 'A', 'Content': 'Hmm hmm hmm .'},
 {'Speaker_Name': 'B',
  'Content': "Are we we're not allowed to dim the lights so people can see that a bit better ?"},
 {'Speaker_Name': 'A', 'Content': 'Yeah .'},
 {'Speaker_Name': 'B', 'Content': "Okay , that's fine ."},
 {'Speaker_Name': 'B', 'Content': 'Am I supposed to be standing up there ?'},
 {'Speaker_Name': 'D', 'Content': "So we've got both of these clipped on ?"},
 {'Speaker_Name': 'B', 'Content': 'Okay .'},
 {'Speaker_Name': 'D', 'Content': 'She gonna answer me or not ?'},
 {'Speaker_Name': 'B', 'Content': "Yeah , I've got Yes ."},
 {'Speaker_Name': 'D', 'Content': 'Right , both of them , okay .'},
 {'Speaker_Name': 'D', 'Content': 'God .'},
 {'Speaker_Name': 'D', 'Content': "Jesus , it's gonna fall off ."},
 {'Speaker_Name': 'A', 'Content': 'Okay .'},
 {'Speaker_Name': 'A', 'Content': 'Yep , yep .'},
 {'Speaker_Name': 'A', 'Content': 'Okay .'},
 {'Speaker_Name': 'B', 'Content': 'Okay .'},
 {'Speaker_Name': 'A', 'Content': 'Tu tu tu tu Hi , good morning .'},
 {'Speaker_Name': 'B', 'Content': 'Hello everybody .'},
 {'Speaker_Name': 'B',
  'Content': "Um I'm Sarah , the Project Manager and this is our first meeting , surprisingly enough ."},
 {'Speaker_Name': 'B',
  'Content': 'Okay , this is our agenda , um we will do some stuff , get to know each other a bit better to feel more comfortable with each other .'},
 {'Speaker_Name': 'B',
  'Content': "Um then we'll go do tool training , talk about the project plan , discuss our own ideas and everything um and we've got twenty five minutes to do that , as far as I can understand ."},
 {'Speaker_Name': 'B',
  'Content': "Now , we're developing a remote control which you probably already know ."},
 {'Speaker_Name': 'B',
  'Content': "Um , we want it to be original , something that's uh people haven't thought of , that's not out in the shops , um , trendy , appealing to a wide market , but you know , not a hunk of metal , and user-friendly , grannies to kids , maybe even pooches should be able to use it ."},
 {'Speaker_Name': 'B',
  'Content': "Okay , um , first is the functional design , um this is where we all go off and do our individual work , um what needs need to be fulfilled by the product , um what effects the product has to have and how it's actually going to do that ."},
 {'Speaker_Name': 'B',
  'Content': "Um , conceptual design , what we're thinking , how it's gonna go and then the detailed design , how we're actually gonna put it into practice and make it work ."},
 {'Speaker_Name': 'A', 'Content': "'Kay ."},
 {'Speaker_Name': 'B', 'Content': 'Okay , right .'},
 {'Speaker_Name': 'B',
  'Content': "We're gonna practice with the pens and draw our favourite animal on the white board , I'll go first , and um sum up the characteristics of that animal ."},
 {'Speaker_Name': 'B',
  'Content': "So Okay , I'll leave space for everyone else ."},
 {'Speaker_Name': 'A', 'Content': 'Oops .'},
 {'Speaker_Name': 'B', 'Content': "Um What's missing ?"},
 {'Speaker_Name': 'B', 'Content': "We're running out of blue ."},
 {'Speaker_Name': 'B', 'Content': 'Okay .'},
 {'Speaker_Name': 'B',
  'Content': "I'm not gonna ask you to guess , I'm going to tell you that's supposed to be a tiger ."},
 {'Speaker_Name': 'A', 'Content': 'Mm .'},
 {'Speaker_Name': 'B',
  'Content': 'And I see them as majestic , and independent , and proud .'},
 {'Speaker_Name': 'A', 'Content': 'Oh sorry .'},
 {'Speaker_Name': 'A', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'B', 'Content': 'Now , who would like to go next ?'},
 {'Speaker_Name': 'A', 'Content': 'Yeah , me .'},
 {'Speaker_Name': 'B', 'Content': "'Kay ."},
 {'Speaker_Name': 'A', 'Content': 'Cat .'},
 {'Speaker_Name': 'A', 'Content': 'Where did this come from ?'},
 {'Speaker_Name': 'B', 'Content': 'Is that your lapel then ?'},
 {'Speaker_Name': 'A', 'Content': 'Uh , yep .'},
 {'Speaker_Name': 'B', 'Content': 'There you go .'},
 {'Speaker_Name': 'A', 'Content': 'Thank you .'},
 {'Speaker_Name': 'A',
  'Content': "Uh , maybe you can guess what I'm trying to make ?"},
 {'Speaker_Name': 'D', 'Content': 'A kind of dog ?'},
 {'Speaker_Name': 'A', 'Content': 'Yep .'},
 {'Speaker_Name': 'A',
  'Content': "It's actually sitting , so it's sitting , it's not standing ."},
 {'Speaker_Name': 'D', 'Content': 'Sorry ?'},
 {'Speaker_Name': 'C', 'Content': "It's sitting down ."},
 {'Speaker_Name': 'D', 'Content': 'Uh .'},
 {'Speaker_Name': 'A',
  'Content': "Okay , I see it as one thing it's very supportive ."},
 {'Speaker_Name': 'A',
  'Content': "It's your best friend and your you can talk to a dog , it can be your best friend , it doesn't discriminate between you , based on what you are ."},
 {'Speaker_Name': 'A',
  'Content': "Second it's loyal and third thing it's got intuition ."},
 {'Speaker_Name': 'A',
  'Content': 'dogs can som sometimes can make out between a thief and a person so basically these are the three unique features I think belong to a dog .'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'B', 'Content': 'Okay , thank you .'},
 {'Speaker_Name': 'A', 'Content': 'Thank you .'},
 {'Speaker_Name': 'C', 'Content': "Yeah I'll have a go ."},
 {'Speaker_Name': 'A', 'Content': 'Okay .'},
 {'Speaker_Name': 'A', 'Content': 'Sorry .'},
 {'Speaker_Name': 'D',
  'Content': "Please , please leave me a space at the bottom , I'm little , you can get to the top , with standing on a chair ."},
 {'Speaker_Name': 'C', 'Content': 'Thanks .'},
 {'Speaker_Name': 'C', 'Content': 'Alright , okay .'},
 {'Speaker_Name': 'C',
  'Content': "Well since you guys have chosen the ones I wanted to do , I'll have to have to go for something a bit random ."},
 {'Speaker_Name': 'B', 'Content': 'Okay .'},
 {'Speaker_Name': 'A', 'Content': 'Does it look like a dog actually ?'},
 {'Speaker_Name': 'C',
  'Content': "And also , my drawing skill isn't that great so , yeah ."},
 {'Speaker_Name': 'B',
  'Content': 'Well , as you can see , the quality of the work today is um Gonna be a bird .'},
 {'Speaker_Name': 'A', 'Content': 'Mm .'},
 {'Speaker_Name': 'D', 'Content': "I think it's outstandingly good ."},
 {'Speaker_Name': 'C',
  'Content': "Okay , now I'm gonna have to change what is was originally gonna be because that looks like a beak now , so ."},
 {'Speaker_Name': 'D', 'Content': 'Crocodile ?'},
 {'Speaker_Name': 'C',
  'Content': 'Yeah , it can be a crocodile , it can be a crocodile .'},
 {'Speaker_Name': 'B', 'Content': "Is it gonna be it's gonna be a bird ."},
 {'Speaker_Name': 'C',
  'Content': 'Well it was it was an at first firstly it was an attempt at a T_ Rex and then it sort of changed into a pelican but it can be a crocodile now actually .'},
 {'Speaker_Name': 'D', 'Content': "O Beauti that's Okay ."},
 {'Speaker_Name': 'B', 'Content': "That's lovely ."},
 {'Speaker_Name': 'C',
  'Content': "Yeah and uh I'll have to think on the spot of uh things that it is ."},
 {'Speaker_Name': 'C',
  'Content': "Um uh scary , uh strong , yeah that's about it I think ."},
 {'Speaker_Name': 'B', 'Content': "Okay it's fine ."},
 {'Speaker_Name': 'D',
  'Content': "Um , I'm very impressed with your artistic skills , mine's are dreadful ."},
 {'Speaker_Name': 'C', 'Content': 'Uh uh Wo Hmm .'},
 {'Speaker_Name': 'D',
  'Content': 'Oops this is now coming apart , let me just put the top in .'},
 {'Speaker_Name': 'D',
  'Content': "I hope that clicks in , I'll just I'll hold it on , okay ."},
 {'Speaker_Name': 'D', 'Content': 'Oops , oh dear , what happened there ?'},
 {'Speaker_Name': 'B', 'Content': 'Technical help .'},
 {'Speaker_Name': 'D',
  'Content': "Hopefully that'll stay on , two-handed version ."},
 {'Speaker_Name': 'C', 'Content': 'Okay .'},
 {'Speaker_Name': 'D',
  'Content': 'Okay , uh Again this is off the top of my head , I was gonna do a big cat too , um .'},
 {'Speaker_Name': 'C', 'Content': 'Uh S Uh Okay , some sort of bird .'},
 {'Speaker_Name': 'D',
  'Content': "Oh dear , it doesn't look what like what I want it to be ."},
 {'Speaker_Name': 'B', 'Content': 'Hmm .'},
 {'Speaker_Name': 'D', 'Content': 'Uh .'},
 {'Speaker_Name': 'D', 'Content': "It's not a vampire bat honestly ."},
 {'Speaker_Name': 'B', 'Content': 'Okay , yeah .'},
 {'Speaker_Name': 'D', 'Content': "Uh and somewhere there's a body behind ."},
 {'Speaker_Name': 'D',
  'Content': "That's my dreadful that's the worst yet , that's it's meant to be an eagle you can tell it's a flying animal could have been a seagull , I never thought of a seagull ."},
 {'Speaker_Name': 'B', 'Content': 'A seagu right , not a seagull .'},
 {'Speaker_Name': 'C', 'Content': 'Ah eagle , right okay .'},
 {'Speaker_Name': 'A', 'Content': 'Eagle , okay .'},
 {'Speaker_Name': 'D',
  'Content': "An eagle , um again I'm thinking on my feet goodness ."},
 {'Speaker_Name': 'D',
  'Content': "I suppose they're all so independent , I'd put that one down again ."},
 {'Speaker_Name': 'D', 'Content': 'Da dum um .'},
 {'Speaker_Name': 'C', 'Content': "They're good at golf ."},
 {'Speaker_Name': 'D',
  'Content': "Indepen independent , right , did you say they're good at golf ?"},
 {'Speaker_Name': 'C', 'Content': 'Yeah , no yeah , an eagle .'},
 {'Speaker_Name': 'D', 'Content': 'Are they ?'},
 {'Speaker_Name': 'B', 'Content': 'Eagle .'},
 {'Speaker_Name': 'D', 'Content': 'Oh .'},
 {'Speaker_Name': 'D', 'Content': "Oh right , okay , I'm not good at golf ."},
 {'Speaker_Name': 'D',
  'Content': "I'd say they're quite free-spirited , flying around everywhere , doing their own thing ."},
 {'Speaker_Name': 'D',
  'Content': "And uh , birds of prey aren't they , oh dear , intrepid ."},
 {'Speaker_Name': 'B', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'D', 'Content': "I'll put that , intrepid ."},
 {'Speaker_Name': 'D',
  'Content': "There we go , hope that pen's gonna be okay ."},
 {'Speaker_Name': 'B', 'Content': "That's lovely ."},
 {'Speaker_Name': 'D', 'Content': 'Whoops .'},
 {'Speaker_Name': 'B', 'Content': 'Okay .'},
 {'Speaker_Name': 'B', 'Content': 'That was fun , right .'},
 {'Speaker_Name': 'B',
  'Content': "Um finance-wise , we've got a selling price at twenty five Euros , which I don't actually know what that is in Pounds , at all ."},
 {'Speaker_Name': 'B', 'Content': 'Any ideas ?'},
 {'Speaker_Name': 'C', 'Content': "It's about mm , mm yeah ."},
 {'Speaker_Name': 'D', 'Content': 'Seventeen .'},
 {'Speaker_Name': 'A', 'Content': 'One point four or something like that .'},
 {'Speaker_Name': 'A',
  'Content': 'One point four Euro would make a Pound or something like that .'},
 {'Speaker_Name': 'C',
  'Content': 'Yeah , yeah , something like that , so that yeah about seventeen , seventeen Pounds , something like that .'},
 {'Speaker_Name': 'A', 'Content': 'Yeah .'},
 {'Speaker_Name': 'B', 'Content': 'D fifteen ?'},
 {'Speaker_Name': 'D', 'Content': 'Seventeen Pounds .'},
 {'Speaker_Name': 'B', 'Content': 'Seventeen .'},
 {'Speaker_Name': 'B', 'Content': "Okay , that's expensive ."},
 {'Speaker_Name': 'D', 'Content': 'Should we be making notes of this ?'},
 {'Speaker_Name': 'D',
  'Content': "We can just refer to this later can't we ?"},
 {'Speaker_Name': 'C',
  'Content': "But Havi having said that though , if you wanna get one of those the the ones on the market at the moment they're s they're about twenty pounds anyway ."},
 {'Speaker_Name': 'B',
  'Content': "I think so , I think so , I'll be able to um pull it up , or I could put it in the shared folder or something ."},
 {'Speaker_Name': 'D', 'Content': 'Yeah , okay .'},
 {'Speaker_Name': 'D', 'Content': 'Okay .'},
 {'Speaker_Name': 'C',
  'Content': "So , it'd still be yeah , we had to buy one ."},
 {'Speaker_Name': 'D', 'Content': 'Right .'},
 {'Speaker_Name': 'B', 'Content': 'Really ?'},
 {'Speaker_Name': 'D',
  'Content': 'So so I suppose later it depends if we want to undercut the price , we d or or is it going to make our product look a cheapie-cheapie option ?'},
 {'Speaker_Name': 'B', 'Content': 'Mm .'},
 {'Speaker_Name': 'B',
  'Content': "I think Yeah , um production cost's at twelve fifty , so half of the selling price is taken up by building it ."},
 {'Speaker_Name': 'C', 'Content': 'Hmm .'},
 {'Speaker_Name': 'A', 'Content': 'Okay , pretty huge margin .'},
 {'Speaker_Name': 'C', 'Content': 'Yeah .'},
 {'Speaker_Name': 'D', 'Content': 'Mm .'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'B',
  'Content': 'Um , and profit aim is fifty million Euros , which is uh Yi yes , um yeah , I presume so .'},
 {'Speaker_Name': 'D', 'Content': 'In our first year ?'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'A', 'Content': 'So then Mm-hmm .'},
 {'Speaker_Name': 'B', 'Content': 'Um Mm-hmm .'},
 {'Speaker_Name': 'D',
  'Content': "You've got market range international and you did say earlier it's got to be a um accessible and usable by sort of all age groups just t we're not focusing on business market , any particular thing , it's everyone user-friendly to everyone ."},
 {'Speaker_Name': 'B', 'Content': 'No , yeah .'},
 {'Speaker_Name': 'D', 'Content': 'Okay .'},
 {'Speaker_Name': 'D', 'Content': 'Big target group .'},
 {'Speaker_Name': 'B',
  'Content': "So yes , yes , I don't think we have to I don't think it's a case of worrying about different languages and things like that , um making that a key point , just that it's going to be in the international market like Australia , America , things like that ."},
 {'Speaker_Name': 'D', 'Content': 'No .'},
 {'Speaker_Name': 'D', 'Content': 'Mm .'},
 {'Speaker_Name': 'B', 'Content': 'Okay .'},
 {'Speaker_Name': 'B',
  'Content': 'What are your experiences with remote controls ?'},
 {'Speaker_Name': 'B',
  'Content': "I mean I've got we got um we had three videos , a T_V_ and a sort of amp thing all set up so we got one of the universal remote controls , um that you programme each of your things into , but that kept losing the signals so we'd have to re-programme it every now and again ."},
 {'Speaker_Name': 'C', 'Content': 'Yeah .'},
 {'Speaker_Name': 'D', 'Content': 'Alright .'},
 {'Speaker_Name': 'C', 'Content': 'Yeah .'},
 {'Speaker_Name': 'A',
  'Content': 'Yeah , that c Okay , you wanna integrate everything into one like Okay .'},
 {'Speaker_Name': 'B',
  'Content': "I think it was quite a cheapie as well , so that might have had something to do with it , but that was quite good , the fact that you could You didn't have six remote controls sitting in front of you ."},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'C', 'Content': 'Yeah uh .'},
 {'Speaker_Name': 'C', 'Content': 'Use all the ones at the same time .'},
 {'Speaker_Name': 'D', 'Content': 'Right .'},
 {'Speaker_Name': 'C', 'Content': "Yeah , 'cause you Yeah ."},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'D',
  'Content': 'My experience has only been being given the remote control with the object I buy , not doing any tampering with it and programming , using it to programme T_V_ and uh uh videos and things .'},
 {'Speaker_Name': 'D',
  'Content': "But basically on , off , volume up and down , channel one , two , th that basic functions , I don't think I could go any further with it than that , so , I suppose it's got to be something usable by someone like me as well ."},
 {'Speaker_Name': 'B', 'Content': 'Mm .'},
 {'Speaker_Name': 'B',
  'Content': "Yeah , the main that's the main stuff anyway , I mean and you don't want to I hate I hate looking at a control and seeing a million tiny little buttons with tiny little words saying what they all do and just sitting there searching for the teletext button or something like that ."},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'D', 'Content': 'Mm .'},
 {'Speaker_Name': 'D', 'Content': 'Mm .'},
 {'Speaker_Name': 'D',
  'Content': "And symbols that you don't necessarily understand , symbols you're meant to understand that you don't ."},
 {'Speaker_Name': 'B', 'Content': 'Yeah .'},
 {'Speaker_Name': 'A',
  'Content': 'So simplification of symbols you could think of .'},
 {'Speaker_Name': 'B', 'Content': 'Um .'},
 {'Speaker_Name': 'B',
  'Content': "When they're when you've got the main things on the front of it and a section opens up or something to the other functions where you can do sound or options kind of recording , things like that inside it ."},
 {'Speaker_Name': 'D', 'Content': 'Oh yeah .'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'B',
  'Content': "'Cause it doesn't make when you pick it up it doesn't make it really complicated to look at , it's obvious what you're doing , um ."},
 {'Speaker_Name': 'D', 'Content': 'Mm .'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'C', 'Content': 'Mm .'},
 {'Speaker_Name': 'D',
  'Content': "Actually that just raises a point , I wonder what our design people think , but you know on a mobile phone , you can press a key and it gives you a menu , it's got a menu display , I wonder if incorporating that into the design of a remote control might be useful , so you've got a little L_C_D_ display ."},
 {'Speaker_Name': 'A', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'A', 'Content': 'Menu , alright .'},
 {'Speaker_Name': 'C', 'Content': 'Yeah .'},
 {'Speaker_Name': 'A',
  'Content': 'Uh uh Right , I was thinking on the same lines you , instead of having too many b buttons and make it complicated for the user , may h maybe have an L_C_D_ di display or something like that , like a mobile , yeah and with menus .'},
 {'Speaker_Name': 'D', 'Content': 'With menus , yeah , yeah .'},
 {'Speaker_Name': 'A',
  'Content': "And if it's s somewhat similar to what you have on mobile phone , people might find it easier to browse and navigate also maybe ."},
 {'Speaker_Name': 'D', 'Content': 'Yeah .'},
 {'Speaker_Name': 'B', 'Content': 'What about the older generation ?'},
 {'Speaker_Name': 'B', 'Content': 'What about granny and grandads ?'},
 {'Speaker_Name': 'B',
  'Content': "Um , my grandad can answer his mobile phone , but he couldn't even dream of texting or something like that ."},
 {'Speaker_Name': 'A', 'Content': 'You mean to save it lesser number .'},
 {'Speaker_Name': 'C', 'Content': 'Yeah .'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'D',
  'Content': 'Can he programme his remote control or is it basic with that too ?'},
 {'Speaker_Name': 'A', 'Content': 'Right .'},
 {'Speaker_Name': 'B',
  'Content': "I don't think they tape things , I don't think they use Mm , yeah , the age gap ."},
 {'Speaker_Name': 'C',
  'Content': "Yeah , my grandad's actually better than me at using teletext , so ."},
 {'Speaker_Name': 'D', 'Content': 'Right .'},
 {'Speaker_Name': 'D', 'Content': 'Right .'},
 {'Speaker_Name': 'D',
  'Content': "So that's a problem regardless of of any design modifications you you come up with , that's gonna be a problem anyway with the older generation perhaps , and that's another issue how we tackle that ."},
 {'Speaker_Name': 'C', 'Content': 'Yeah .'},
 {'Speaker_Name': 'C',
  'Content': "Yeah , what it just needs to be as long as it's sort of self-intuitive and you can can work out what everything's doing , 'cause I mean , menus on sort of new phones now they've sort of got all these pictures and stuff which makes it fairly obvious what you're trying to do ."},
 {'Speaker_Name': 'B', 'Content': 'Mm .'},
 {'Speaker_Name': 'A', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'B',
  'Content': "I don't know , I d I don't like the , you know the new phones that have kind of got a Windows-based running system ."},
 {'Speaker_Name': 'C', 'Content': "But I don't know how Oh yeah ."},
 {'Speaker_Name': 'D', 'Content': 'Mm-hmm .'},
 {'Speaker_Name': 'B',
  'Content': "I find it really confusing , I kept getting lost in the phone , I di I've not got a new one but uh my friend got a new one and I was trying to do things with it and I just kept getting lost , but that's just me ."},

In [ ]:
df2= pd.read_csv(filepath)

In [100]:
import os
import random
import shutil

data_folder = 'data'
summary_folder = 'summary'
output_folder = 'output'

# Set the seed for random shuffling
random.seed(42)

# Create output folders
train_folder = os.path.join(output_folder, 'train')
test_folder = os.path.join(output_folder, 'test')
valid_folder = os.path.join(output_folder, 'valid')

os.makedirs(train_folder, exist_ok=True)
os.makedirs(test_folder, exist_ok=True)
os.makedirs(valid_folder, exist_ok=True)

# Get the list of file names in the data folder
data_file_names = [file_name for file_name in os.listdir(data_folder) if file_name.endswith('.csv')]

# Shuffle the file names
random.shuffle(data_file_names)

# Calculate the number of files for each set
num_files = len(data_file_names)
train_size = int(0.7 * num_files)
test_size = int(0.15 * num_files)
valid_size = num_files - train_size - test_size

# Split the files into train, test, and validation sets
train_files = data_file_names[:train_size]
test_files = data_file_names[train_size:train_size + test_size]
valid_files = data_file_names[train_size + test_size:]

# Move data files to train folder
for file_name in train_files:
    src_path = os.path.join(data_folder, file_name)
    dest_path = os.path.join(train_folder, file_name)
    shutil.copyfile(src_path, dest_path)

# Move summary files to train folder
for file_name in train_files:
    summary_file_name = os.path.splitext(file_name)[0] + '.txt'
    src_path = os.path.join(summary_folder, summary_file_name)
    dest_path = os.path.join(train_folder, summary_file_name)
    shutil.copyfile(src_path, dest_path)

# Move data files to test folder
for file_name in test_files:
    src_path = os.path.join(data_folder, file_name)
    dest_path = os.path.join(test_folder, file_name)
    shutil.copyfile(src_path, dest_path)

# Move summary files to test folder
for file_name in test_files:
    summary_file_name = os.path.splitext(file_name)[0] + '.txt'
    src_path = os.path.join(summary_folder, summary_file_name)
    dest_path = os.path.join(test_folder, summary_file_name)
    shutil.copyfile(src_path, dest_path)

# Move data files to validation folder
for file_name in valid_files:
    src_path = os.path.join(data_folder, file_name)
    dest_path = os.path.join(valid_folder, file_name)
    shutil.copyfile(src_path, dest_path)

# Move summary files to validation folder
for file_name in valid_files:
    summary_file_name = os.path.splitext(file_name)[0] + '.txt'
    src_path = os.path.join(summary_folder, summary_file_name)
    dest_path = os.path.join(valid_folder, summary_file_name)
    shutil.copyfile(src_path, dest_path)

print("Splitting files into train, test, and valid folders completed!")

Splitting files into train, test, and valid folders completed!

In [107]:
%%time

import os
import pandas as pd

data_folder = 'data'

# Get the list of CSV files in the data folder
csv_files = [file for file in os.listdir(data_folder) if file.endswith('.csv')]

# Loop through each CSV file
for csv_file in csv_files:
    csv_file_path = os.path.join(data_folder, csv_file)

    # Read the CSV file
    df = pd.read_csv(csv_file_path)

    # Remove the second and fourth columns
    columns_to_remove = [1, 3]  # Index positions of columns to remove
    df.drop(df.columns[columns_to_remove], axis=1, inplace=True)

    # Save the modified dataframe back to CSV
    output_csv_file_path = os.path.join(data_folder, f"modified_{csv_file}")
    df.to_csv(output_csv_file_path, index=False)

print("Columns removed and modified files saved successfully.")

Columns removed and modified files saved successfully.
CPU times: total: 125 ms
Wall time: 606 ms

In [119]:
import csv
import os

folder_path = 'data'
output_strings = []

# Get the list of CSV files in the folder
file_list = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Iterate over each file in the folder
for file in file_list:
    file_path = os.path.join(folder_path, file)
    file_string = ''

    # Read the CSV file
    with open(file_path, 'r') as file:
        reader = csv.reader(file)

        # Iterate over each row in the CSV file
        for row in reader:
            # Combine the row elements into a single string
            row_string = ': '.join(row)

            # Append the row string to the file string
            file_string += row_string + '\n'

    # Add the file string to the output list
    output_strings.append(file_string)

# Print the output list of strings
#print(output_strings)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [133]:
len(output_strings)

137

In [134]:
import os

folder_path = 'summary'
output_summaries = []

# Get the list of .txt files in the folder
file_list = [file for file in os.listdir(folder_path) if file.endswith('.txt')]

# Iterate over each file in the folder
for file in file_list:
    file_path = os.path.join(folder_path, file)

    # Read the contents of the .txt file
    with open(file_path, 'r') as file:
        file_content = file.read()

    # Add the file content to the output list
    output_summaries.append(file_content)

# Print the output list of strings
print(output_summaries)

['The project manager introduced the upcoming project to the team members and then the team members participated in an exercise in which they drew their favorite animal and discussed what they liked about the animal.\nThe project manager talked about the project finances and selling prices.\nThe team then discussed various features to consider in making the remote.\nThe industrial designer will work on the working design of the remote.\nThe user interface designer will work on the technical functions of the remote.\nThe marketing executive will work on what requirements the remote has to fulfill\nThe remote will sell for 25 Euro.\nThe remote will be sold on an international scale.\nThe production costs cannot exceed 12.50 Euro.\nWhether the remote will be used exclusively for televisions.\n', 'The project manager briefed the team on some new requirements to consider when designing the remote.\nThe user interface designer presented two existing products and discussed what was wrong with each product.\nThe team discussed how to create a remote which did not include the problems present in the existing products presented by the interface specialist.\nThe marketing expert presented consumer preferences and requirements and the team discussed who their target demographic should be and whether to include speech recognition in their product.\nThe industrial designer discussed the interior workings of a remote and the team discussed various options for components and energy sources.\nThe team then discussed features to include in the remote and what they could do to figure out how to categorize them.\nThe industrial designer will work on the components concept.\nThe user interface designer will work on the user interface.\nThe marketing expert will work on trend watching\nThe team will not work with teletext.\nThe remote will only control televisions.\nThe corporate color and design must be incorporated into the design of the remote.\nThe remote will have buttons for the following functions: on and off, channel up and down, volume up and down, and entering channel numbers.\nThe remote has to look good and be easy to use.\nThe target demographic is people aged fifteen to thirty five.\nThe remote will use an infra-red sensor.\nThe remote will use regular batteries.\nHow to categorize the functions on the remote.\nHow to implement the categorization of functions in the design of the remote.\nDefining a target demographic.\nWhether to include speech recognition as a feature in the remote.\nHow to incorporate more advanced functions into the remote while keeping the design and usability of the remote simple.\n', "The project manager recapped the decisions made in the previous meeting.\nThe marketing expert discussed his findings from trend watching reports, stressing the need for a product that has a fancy look and feel, is technologically innovative, is easy to use, and incorporates some aspect of fruit and vegetables in its design.\nThe interface specialist presented research on the appearance of current remotes, concluding that current remotes are generally unappealing in terms of look and usability.\nThe interface specialist presented ideas on how to remedy the unappealing aspects of current remotes in the team's design and also how to incorporate the corporate color scheme into the design.\nThe industrial designer presented options for materials, components, and batteries and discussed the restrictions involved in using certain materials.\nThe team then discussed options for the shape and color scheme of the remote, as well as what components, batteries, and materials to use.\nSome team members will design a prototype of the remote\nThe remote will be curvy.\nThe remote will be shaped like a snowman.\nThe remote will not have a talk-back function.\nThe remote will have a jog dial.\nThe materials used will be plastic and rubber.\nThe case will have a soft fruit-like feel to it.\nThe remote will not have an LCD display.\nThe remote will have a kinetic battery.\nThe remote will have rubber buttons.\nWhat sort of battery to use.\nHow to incorporate a fruit and vegetable theme, the corporate color, and soft materials into the remote.\nWhat shape the remote should be.\nWhether the remote should have a talk-back function.\nWhether to have an LCD display on the remote.\nWhat the case will look like.\nWhether to include a jog dial on the remote.\n", 'The project manager recapped the decisions made in the previous meeting and two team members presented their prototype and discussed the features the prototype contained.\nThe team then looked at the production costs of the remote and had to decide which features to retain or lose in order to maintain the target cost.\nIn maintaining the target cost, the team had to lose a number of features which they originally wanted, such as a kinetic battery, an LCD display, and various color options.\nThe team then evaluated the prototype on the basis of its appearance, technological innovation, and spongy quality.\nThe prototype did fairly well in the evaluation.\nThe team then conducted an evaluation of the project process.\nThe team felt that their creativity was hindered by the project budget and their inability to discuss the project outside of their meetings and that the structure of the task did not foster teamwork.\n*NA*\nThe remote will not contain a kinetic battery.\nThe remote will have a regular chip.\nThe case will be double-curved.\nThe remote will have push buttons.\nThe remote will not feature an LCD display.\nThe display will be on the television instead of on the remote.\nThe buttons will be normal colored.\nThe remote will have square buttons.\nMeeting the target cost.\n', 'The team members introduced themselves to each other by name and by their roles in the project.\nThe project manager introduced the upcoming project to the team and then the team members participated in an exercise in which they drew their favorite animal and discussed why they liked the animal.\nThe project manager discussed the project finances and selling prices.\nThe team then discussed various features to consider in producing the remote such as gaming options, an LCD screen, and combining functionality so as to control multiple devices.\nThe team will decide how the user interface will work\nThe remote will cost 12.50 Euro to produce.\nThe remote will sell for 25 Euro.\nThe remote will feature an ergonomic design.\nPutting an LCD screen on the remote.\nHaving a remote that controls multiple devices.\nHaving a joystick on the remote.\n', 'The project manager recapped the events of the previous meeting and briefed the team on some new requirements the team must follow when designing the remote.\nThe marketing expert presented research on consumer preferences and user requirements for remotes.\nThe marketing expert also presented information regarding voice recognition and what demographic finds the feature appealing.\nThe user interface designer described the technical functions of a remote and stressed the need for a user focused design.\nThe industrial designer discussed the interior workings of a remote.\nThe team then discussed the option to include voice recognition, LCD, and a feature to locate a misplaced remote.\nThe team briefly discussed who they were aiming their product to along with the idea of marketing their product to television manufacturers.\nThe team also decided on some features to include in their product.\n*NA*\nThe team will not work with teletext.\nThe remote will only control televisions.\nThe corporate image must be recognizable on the remote.\nThe remote will have a power button.\nThe remote will have a small joystick.\nThe remote will have LCD.\nThe remote will have a menu button.\nInstead of an "okay" button, the user will push down on the joystick.\nThe remote will have a beeping noise which goes off when a user is trying to locate it.\nWhether to include voice recognition as a feature on the remote.\nWhether to include LCD.\nWhat functions the joystick controls.\nWhat functions the LCD controls.\nHaving a remote which controls multiple devices.\nWhat sort of components are necessary for the feature which allows the user to locate a misplaced remote.\n', 'The project manager recapped the decisions made in the previous meeting.\nThe industrial designer presented options for batteries, materials and shapes to use for the case, buttons, and chips.\nThe user interface designer discussed how to create an interface for an ergonomic remote which conforms to the shape and movements of the human hand, as well as an option in which users could connect their remotes to computers in order to download program settings.\nThe marketing expert discussed findings from trendwatching reports, which indicated a need for products which look fancy, are technologically innovative, are easy to use, have a fruit and vegetable theme, and are spongy.\nThe team then discussed what materials and components to use, the color of the remote, and programming options for the remote.\nThe industrial designer and user interface designer will work on a prototype.\nThe marketing expert will work on a product evaluation\nThe remote will use a lithium battery.\nThe remote will have a double curved design.\nThe remote will have a case made of rubber.\nThe remote will be yellow.\nHaving a feature on the remote which allows the user to use a computer to program the remote according to the television model he owns.\nWhere to place the company slogan on the remote.\n', "The project manager recapped the decisions made in the previous meeting and two team members presented a prototype for the remote the team is designing and discussed its ergonomic appearance and its features.\nThe marketing expert began to lead the team in conducting an evaluation of the prototype but was interrupted when the project manager shifted the discussion to examining the production costs of the team's product.\nThe original specifications of the team's product proved to be too expensive and so the team had to discuss which features to lose and which to maintain in order to meet the target cost.\nAfter discussing costs, the team returned to conducting their product evaluation.\nThe prototype was evaluated on the basis of its ability to be located when misplaced, ease of use, appearance, technological innovativeness, and sponginess.\nOverall, the prototype received average marks.\nThe team then evaluated the project process, finding that they were happy overall but quite displeased with the small budget.\n*NA*\nThe remote will feature an LCD.\nThe case for the remote will be single curved.\nThe remote will be designed in a special color.\nThe remote will be made of plastic instead of rubber.\nMeeting the target cost.\nWhether to keep the LCD.\nWhether to have a double curved or single curved case.\n", "The Project Manager gave an introduction to the goal of the project, to create a trendy yet user-friendly remote.\nShe presented a long-range agenda for the whole project.\nThe group introduced themselves to each other and practiced with the meeting room tools by drawing on the board.\nThe Project Manager presented the project budget, the projected price point, and the projected profit aim for the project.\nThen the group began a discussion about their own experiences with remote controls to generate initial design ideas for making the product user-friendly.\nThey discussed grouping features into a menu and adding an LCD display.\nThey also discussed the look of various materials that may be used in the design, in keeping with the company's goal to create fashionable electronics.\nThe group will prepare for the functional design meeting to discuss the components and functions of the product.\nNA.\nThere may not be enough money in the budget to allow the addition of all the features the group discussed, such as the LCD display.\n", "The Industrial Designer gave his presentation on the basic functions of the remote.\nHe presented the basic components that remotes share and suggested that smaller batteries be considered in the product design.\nThe User Interface Designer presented his ideas for making the remote easy-to-use; he discussed using a simple design and hiding complicated features from the main interface.\nThe Marketing Expert presented the findings from a lab study on user requirements for a remote control device, and discussed users' demand for a simple interface and advanced technology.\nThe Project Manager presented the new requirements that the remote not include a teletext function, that it be used only to control television, and that it include the company image in its design.\nThe group narrowed down their target marketing group to the youth market.\nThey discussed the functions the remote will have, including Video Plus capability and rechargeable batteries.\nA customer service plan was suggested to make the remote seem more user-friendly, but it was decided that helpful manuals were more within the budget.\nThe group then discussed the shell-like shape of the remote and including several different casing options to buyers.\nThe Marketing Expert will research consumers' opinions on instruction manuals.\nIt was decided that the group will produce one product design instead of creating alternate designs in an attempt to accomodate different users' preferences.\nThe marketing will be focused towards a young, business-class buyer.\nThe remote will feature Video Plus capabilities and a seashell-like shape to accomodate the LCD display and the flip screen.\nThe remote will be bundled with a docking station to recharge the remote's batteries and a user-friendly instruction manual, and multiple casings will be made available.\nThe limitations of the budget will restrict the development of some features; several of the features that the group wanted to include may have to be made simpler to decrease cost.\n", 'The Project Manager reviewed the decisions from the previous meeting.\nThe Marketing Expert made a presentation on trend watching, including trends in user requirements and trends in fashion.\nThe Industrial Designer presented all the components of the device and announced that several of the features already discussed would not be available.\nHe suggested substituting a kinetic battery for the rechargeable batteries and using a combination of rubber and plastic for the materials.\nThe User Interface Designer presented his main interface design, which included buttons for the most frequently used features and a graphic user interface on the LCD screen for other functions, to keep frequently used features easy to use.\nHe announced that speech recognition was still an option to consider, depending on price.\nThe Project Manager then began a discussion to decide what was going into the final design.\nIt was decided that a kinetic battery would be used in place of a rechargeable battery, that the remote will feature an LCD screen and rubber casing and rubber buttons, and that interchangeable rubber covers in fruit colors will be available.\nSpeech recognition may be included if it is not too costly.\nIt was decided that the remote would feature an LCD screen, rubber buttons, colorful rubber changeable skins, a kinetic battery, and possibly speech recognition if it is still within the budget to include it.\nSeveral of the features that the group had wanted to integrate into the design were either too costly or unavailable due to new limitations from the factory.\nThe group had to change many of the original design elements to an alternative.\n', "The Project Manager went over decisions from the previous meeting.\nThe Industrial Designer presented the prototype and discussed its look, its internal components, and its interface.\nThe Marketing Expert evaluated the product according to the initial product goals.\nThe group then decided that enough of this criteria had been satisfied for the project to continue.\nThe Project Manager presented the final cost of the device which exceeded the initial projected price point.\nThe group decided to remove speech recognition but to propose to the management that it  remain in the design.\nThe group then discussed their effectiveness as a team.\nAll members felt that they interacted well and that they felt they could be creative.\nThe Marketing Expert felt that the market-research based approach would help the project's success with consumers.\nThe group did express, however, that the budget was overly constraining.\nThe Project Manager instructed the group to fill out a final evaluation questionnaire.\nThe group will suggest to the management that speech recognition remain in the product design.\nAll members will fill out a final evaluation questionnaire.\nIt was decided that the speech recognition component seemed feasible, so it was added to the prototype design to provide a device locator function.\nIt was removed when the project exceeded its initial budget, but it will be suggested to the management that the speech recognition should remain in the product design.\nThe plastic case will be a neutral color, and the changeable rubber cases will be available in vibrant, fruit colors.\nThe LCD screen will appear only in black and white.\nThe company logo will appear on the inside of the device when opened.\nThe group decided that the device fulfilled enough of the project's initial goals to continue in production.\nThere was a lack of cost information at the beginning of the project.\nThe group did not know how much the features made available to them actually cost until the prototype was constructed; their prototype design may have been different had this information been available at the beginning.\n", "The group discussed their initial ideas about the features that they wanted to integrate into the design.\nThey discussed making a universal remote with a locator function.\nThey also discussed the shape and the number of functions in the main interface.\nThe Project Manager instructed the Marketing Expert to examine competitors' remotes, the User Interface Designer to research possible shapes and colors, and the Industrial Designer to research possible materials and the necessary internal components of the device.\nThe Marketing Expert will examine the features and design of competitors' remotes.\nThe User Interface Designer will research possible shapes and colors for the device.\nThe Industrial Designer will research possible materials and the necessary internal components of the device.\nNA.\nNA.\n", "The Marketing Expert presented requirements of users as found in a company market study.\nThe study showed that users want a fancier-looking but uncomplicated remote control, and are interested in speech recognition.\nHe presented the age groups polled and said that the target marketing group should be users aged fifteen to thirty-five.\nThe User Interface Designer presented several competitors' remotes and discussed the features that would make their own device more user-friendly.\nThe Industrial Designer gave a presentation on important internal components that would keep the project within its budget, and discussed possible materials and programmable features.\nThe Project Manager gave several new requirements for the project to the group.\nThe group discussed the features they would like to incorporate into the design in light of the new requirements and budget constraints.\nThey decided to keep speech recognition as one of their components, and decided to include some programmable features, limit the number of button functions, and make the remote yellow and glow-in-the-dark, in an organic shape.\nThe Program Manager said that he would ask to what extent the company motto had to be incorporated into the design.\nThe Project Manager will ask to what extent the company logo must be incorporated into the design.\nThe remote will feature speech recognition and programmable channel and volume pre

In [137]:
print(output_summaries[0])

The project manager introduced the upcoming project to the team members and then the team members participated in an exercise in which they drew their favorite animal and discussed what they liked about the animal.
The project manager talked about the project finances and selling prices.
The team then discussed various features to consider in making the remote.
The industrial designer will work on the working design of the remote.
The user interface designer will work on the technical functions of the remote.
The marketing executive will work on what requirements the remote has to fulfill
The remote will sell for 25 Euro.
The remote will be sold on an international scale.
The production costs cannot exceed 12.50 Euro.
Whether the remote will be used exclusively for televisions.

In [138]:
print(output_strings[0])

B: Okay .
B: Right .
B: Um well this is the kick-off meeting for our our project .
B: Um and um this is just what we're gonna be doing over the next twenty five minutes .
D: Mm-hmm .
B: Um so first of all , just to kind of make sure that we all know each other , I'm Laura and I'm the project manager .
B: Do you want to introduce yourself again ?
D: Great .
A: Hi , I'm David and I'm supposed to be an industrial designer .
B: Okay .
D: And I'm Andrew and I'm uh our marketing expert .
C: Um I'm Craig and I'm User Interface .
B: Great .
B: Okay .
B: Um so we're designing a new remote control and um Oh I have to record who's here actually .
B: So that's David , Andrew and Craig , isn't it ?
B: And you all arrived on time .
B: Um yeah so des uh design a new remote control .
B: Um , as you can see it's supposed to be original , trendy and user friendly .
B: Um so that's kind of our our brief , as it were .
B: Um and so there are three different stages to the design .
B: Um I'm not really sure what what you guys have already received um in your emails .
B: What did you get ?
A: Um , I just got the project announcement about what the project is .
B: Mm-hmm .
A: Designing a remote control .
D: Mm-hmm .
A: That's about it , didn't get anything else .
D: Mm-hmm .
D: Yeah , that's that's it .
B: Is that what everybody got ?
C: Yeah .
A: Did you get the same thing ?
B: Okay .
D: Yeah .
B: Um .
B: So we're gonna have like individual work and then a meeting about it .
B: And repeat that process three times .
B: Um and at this point we get try out the whiteboard over there .
B: Um .
B: So uh you get to draw your favourite animal and sum up your favourite characteristics of it .
B: So who would like to go first ?
D: I will go .
D: That's fine .
B: Very good .
D: Alright .
D: So This one here , right ?
B: Mm-hmm .
D: Okay .
D: Very nice .
D: Alright .
D: My favourite animal is like A beagle .
D: Um charac favourite characteristics of it ?
D: Is that right ?
B: Yeah .
D: Uh , right , well basically um high priority for any animal for me is that they be willing to take a lot of physical affection from their family .
B: Yeah .
D: And , yeah that they have lots of personality and uh be fit and in robust good health .
D: So this is blue .
D: Blue beagle .
D: My family's beagle .
B: Right .
B: Lovely .
C: Well , my favourite animal would be a monkey .
C: Then they're small cute and furry , and uh when planet of the apes becomes real , I'm gonna be up there with them .
B: Right .
A: Cool .
A: There's too much gear .
B: You can take as long over this as you like , because we haven't got an awful lot to discuss .
B: Ok oh we do we do .
B: Don't feel like you're in a rush , anyway .
A: Okay .
D: I coulda told you a whole lot more about beagles .
B: Ach why not We might have to get you up again then .
D: Boy , let me tell you .
B: I don't know what mine is .
B: I'm gonna have to think on the spot now .
D: Impressionist .
A: Can't draw .
B: Is that a whale ?
A: Um .
A: Yeah .
A: Um , well anyway , I don't know , it's just the first animal I can think off the top of my head .
A: Um .
A: Yes .
A: Big reason is 'cause I'm allergic to most animals .
A: Allergic to animal fur , so um fish was a natural choice .
B: Ah .
A: Um , yeah , and I kind of like whales .
A: They come in and go eat everything in sight .
A: And they're quite harmless and mild and interesting .
D: Alright .
D: Mm .
B: Okay .
B: God , I still don't know what I'm gonna write about .
B: Um .
D: Superb sketch , by the way .
A: Tail's a bit big , I think .
B: I was gonna choose a dog as well .
B: But I'll just draw a different kind of dog .
D: Yep .
B: M my favourite animal is my own dog at home .
B: Um That doesn't really look like him , actually .
B: He looks more like a pig , actually .
B: Ah well .
D: I see a dog in there .
B: Do you ?
D: Yep .
B: Oh that's very good of you .
D: Now I see a rooster .
B: Uh .
D: What kind is it ?
B: Um he's a mixture of uh various things .
B: Um and what do I like about him , um That's just to suggest that his tail wags .
B: Um he's very friendly and cheery and always pleased to see you , and very kind of affectionate and um uh and he's quite quite wee as well so you know he can doesn't take up too much space .
B: Um and uh And he does a funny thing where he chases his tail as well , which is quite amusing , so It is .
D: Is he aware that th it's his own cha tail he's chasing ?
B: I think it is .
B: He only does it after he's had his dinner and um he'll just all of a sudden just get up and start chasing his tail 'round the living room .
D: Hmm .
A: It's an after dinner dog then .
B: Yeah , so uh Yeah , maybe .
D: Probably when he was little he got lots of attention for doing it and has forever been conditioned .
B: Maybe .
B: Right , um where did you find this ?
B: Just down here ?
B: Yeah .
B: Okay .
B: Um what are we doing next ?
B: Uh um .
B: Okay , uh we now need to discuss the project finance .
B: Um so according to the brief um we're gonna be selling this remote control for twenty five Euro , um and we're aiming to make fifty million Euro .
B: Um so we're gonna be selling this on an international scale .
B: And uh we don't want it to cost any more than uh twelve fifty Euros , so fifty percent of the selling price .
D: 'Kay .
D: Um , can we just go over that again ?
B: Sure .
D: Uh , so bas at twel Alright , yeah .
D: Okay .
D: So cost like production cost is twelve fifty , but selling price is is that wholesale or retail ?
B: All together .
D: Like on the shelf .
B: Um I dunno .
B: I imagine That's a good question .
D: Our sale our sale anyway .
B: I imagine it probably is our sale actually because it's probably up to the the um the retailer to uh sell it for whatever price they want .
D: Yeah , okay okay .
D: Okay .
D: Mm-hmm .
B: Um .
D: Alright .
B: But I I don't know , I mean do you think the fact that it's going to be sold internationally will have a bearing on how we design it at all ?
D: Yes .
B: Think it will ?
D: Mm-hmm .
B: Um .
D: Mm-hmm .
B: Hmm .
D: Well right away I'm wondering if there's um th th uh , like with D_V_D_ players , if there are zones .
B: Oh yeah , regions and stuff , yeah .
D: Um f frequencies or something um as well as uh characters , um different uh keypad styles and s symbols .
B: Yeah .
B: Okay .
A: Hmm .
B: Yeah .
B: Well for a remote control , do you think that will be I suppose it's depends on how complicated our remote control is .
D: Um .
D: I don't know .
D: Yeah .
A: It does make sense from maybe the design point of view 'cause you have more complicated characters like European languages , then you need more buttons .
B: Yeah , yeah .
D: Yeah .
A: So , possibly .
D: Yeah .
B: Okay .
D: And then a and then al the other thing international is on top of the price .
D: I'm thinking the price might might appeal to a certain market in one region , whereas in another it'll be different , so Just a chara just a characteristic of the Just Or just like , basic product podi positioning , the twenty five Euro remote control might be a big hit in London , might not be such a big hit in Greece , who knows , something like that , yeah .
B: What , just like in terms of like the wealth of the country ?
B: Like how much money people have to spend on things like ?
B: Aye , I see what you mean , yeah .
B: Marketing .
B: Good marketing thoughts .
D: Yep .
B: Oh gosh , I should be writing all this down .
B: Um .
D: Right away I'm making some kind of assumptions about what what information we're given here , thinking , 'kay trendy probably means something other than just basic , something other than just standard .
B: Mm .
B: Yeah .
D: Um so I'm wondering right away , is selling twenty five Euros , is that sort of the thi is this gonna to be like the premium product kinda thing or Uh-huh .
B: Yeah , yeah .
B: Like how much does , you know , a remote control cost .
B: Well twenty five Euro , I mean that's um that's about like eighteen pounds or something , isn't it ?
D: Mm-hmm .
B: Or no , is it as much as that ?
B: Sixteen seventeen eighteen pounds .
D: Yep .
D: Yeah , I'd say so , yeah .
B: Um , I dunno , I've never bought a remote control , so I don't know how how good a remote control that would get you .
D: No .
D: Yeah , yeah .
B: Um .
B: But yeah , I suppose it has to look kind of cool and gimmicky .
D: Mm-hmm .
B: Um right , okay .
B: Let me just scoot on ahead here .
B: Okay .
B: Um well d Does anybody have anything to add to uh to the finance issue at all ?
D: Do we have any other background information on like how that compares to other other Yeah .
B: Thin No , actually .
B: That would be useful , though , wouldn't it , if you knew like what your money would get you now .
A: Hmm .
D: Mm-hmm .
B: Mm-hmm .
D: Yeah , interesting thing about discussing um production of a remote control for me is that l as you point out , I just don't think of remote controls as somethin something people consciously assess in their purchasing habits .
B: Yeah , yeah .
D: It's just like getting shoelaces with shoes or something .
B: Oh .
D: It just comes along .
B: Five minutes to end of meeting .
B: Oh , okay .
B: We're a bit behind .
D: Do you know what I mean ?
C: Yeah .
D: Like so sort of like how do you I I mean one one way of looking at it would be , well the people producing television sets , maybe they have to buy remote controls .
A: Yeah .
D: Or another way is maybe people who have T_V_ sets are really fed up with their remote control and they really want a better one or something .
C: I know um My parents went out and bought um remote controls because um they got fed up of having four or five different remote controls for each things the house .
D: But Right .
D: Right .
C: So um for them it was just how many devices control .
D: Okay so Right , so in function one of the priorities might be to combine as many uses I think so .
B: Yeah .
B: Right , so do you think that should be like a main design aim of our remote control d you know , do your your satellite and your regular telly and your V_C_R_ and everything ?
D: Yeah , yeah .
D: Yeah .
D: Well like um , maybe what we could use is a sort of like a example of a successful other piece technology is palm palm pilots .
D: They're gone from being just like little sort of scribble boards to cameras , M_P_ three players , telephones , everything , agenda .
B: Mm-hmm .
D: So , like , I wonder if we might add something new to the to the remote control market , such as the lighting in your house , or um Yeah , yeah .
B: Yeah .
B: Or even like , you know , notes about um what you wanna watch .
B: Like you might put in there oh I want to watch such and such and look a Oh that's a good idea .
D: An Yeah .
B: So extra functionalities .
D: Like , p personally for me , at home I've I've combined the um the audio video of my television set and my D_V_D_ player and my C_D_ player .
D: So they w all work actually function together but I have different remote controls for each of them .
B: Mm-hmm .
D: So it's sort of ironic that that then they're in there um you know , the sound and everything it's just one system .
D: But each one's got its own little part .
B: Hmm .
B: Um okay , uh I'd wel we're gonna have to wrap up pretty quickly in the next couple of minutes .
B: Um I'll just check we've nothing else .
B: Okay .
B: Um so anything else anybody wants to add about what they don't like about remote controls they've used , what they would really like to be part of this new one at all ?
A: And you keep losing them .
B: You keep losing them .
D: Mm .
B: Okay .
A: Finding them is really a pain , you know .
D: Mm .
A: I mean it's usually quite small , or when you want it right , it slipped behind the couch or it's kicked under the table .
D: Mm .
D: Mm-hmm .
D: Mm-hmm .
B: Yeah .
D: Yeah .
B: W You get those ones where you can , if you like , whistle or make a really high pitched noise they beep .
D: Yeah .
A: You know .
D: That's just really good id Yep .
B: There I mean is that something we'd want to include , do you think ?
D: Uh , sure .
B: Dunno .
B: Okay maybe .
D: I remember when the first remote control my my family had was on a cable .
D: Actually had a cable between it and the T_V_ and big like buttons that sort of like , like on a blender or something .
B: My goodness .
D: And um , you know , when I think about what they are now , it's better , but actually it's still kind of , I dunno , like a massive junky thing on the table .
B: Still feels quite primitive .
D: Maybe we could think about how , could be more , you know , streamlined .
B: Maybe like a touch screen or something ?
D: S Something like that , yeah .
B: Okay .
D: Or whatever would be technologically reasonable .
B: Uh-huh , okay .
B: Well I guess that's up to our industrial designer .
D: 'Cause it could b it could it could be that f it could be that functionally that doesn't make it any better , but that just the appeal of of not having You know , these days there's a r pe things in people's homes are becoming more and more like chic , you know .
B: It looks better .
B: Yeah .
D: Um , nicer materials and might be be worth exploring anyway .
B: Okay .
B: Okay .
C: Uh .
B: Right , well um so just to wrap up , the next meeting's gonna be in thirty minutes .
B: So that's about um about ten to twelve by my watch .
B: Um so inbetween now and then , um as the industrial designer , you're gonna be working on you know the actual working design of it so y you know what you're doing there .
A: Yep .
B: Um for user interface , technical functions , I guess that's you know like what we've been talking about , what it'll actually do .
B: Um and uh marketing executive , you'll be just thinking about what it actually what , you know , what requirements it has to has to fulfil and you'll all get instructions emailed to you , I guess .
D: Okay .
B: Um .
B: Yeah , so it's th the functional design stage is next , I guess .
B: And uh and that's the end of the meeting .
B: So I got that little message a lot sooner than I thought I would , so Mm-hmm .
D: Um .
D: Before we wrap up , just to make sure we're all on the same page here , um , do we We were given sort of an example of a coffee machine or something , right ?
B: Uh-huh , yeah .
A: Mm-hmm .
D: Well , um are we at ma right now on the assumption that our television remote control may have features which go beyond the television ?
D: Or are we keeping sort of like a a design commitment to television features ?
B: Th Okay , well just very quickly 'cause this we're supposed to finish now .
D: I I don't know .
D: Yep .
B: Um I guess that's up to us , I mean you probably want some kind of unique selling point of it , so um , you know Yeah .
D: Yeah , sure .
D: Okay .
A: I think one factor would be production cost .
D: Okay , yeah .
A: Because there's a cap there , so um depends on how much you can cram into that price .
D: Okay .
B: Mm-hmm .
D: Okay .
A: Um .
B: Yeah .
A: I think that that's the main factor .
B: Okay .
D: Okay .
B: Right , okay , we'll that's that's the end of the meeting , then .
D: Alright .
B: Um .
B: So , uh thank you all for coming .
A: Cool .

In [141]:
import pandas as pd

# Create a dictionary with column names as keys and lists as values
data = {'Dialogue': output_strings, 'Summaries': output_summaries}

# Create a dataframe from the dictionary
df = pd.DataFrame(data)

In [144]:
df['Dialogue'][0]

B: Okay .
B: Right .
B: Um well this is the kick-off meeting for our our project .
B: Um and um this is just what we're gonna be doing over the next twenty five minutes .
D: Mm-hmm .
B: Um so first of all , just to kind of make sure that we all know each other , I'm Laura and I'm the project manager .
B: Do you want to introduce yourself again ?
D: Great .
A: Hi , I'm David and I'm supposed to be an industrial designer .
B: Okay .
D: And I'm Andrew and I'm uh our marketing expert .
C: Um I'm Craig and I'm User Interface .
B: Great .
B: Okay .
B: Um so we're designing a new remote control and um Oh I have to record who's here actually .
B: So that's David , Andrew and Craig , isn't it ?
B: And you all arrived on time .
B: Um yeah so des uh design a new remote control .
B: Um , as you can see it's supposed to be original , trendy and user friendly .
B: Um so that's kind of our our brief , as it were .
B: Um and so there are three different stages to the design .
B: Um I'm not really sure what what you guys have already received um in your emails .
B: What did you get ?
A: Um , I just got the project announcement about what the project is .
B: Mm-hmm .
A: Designing a remote control .
D: Mm-hmm .
A: That's about it , didn't get anything else .
D: Mm-hmm .
D: Yeah , that's that's it .
B: Is that what everybody got ?
C: Yeah .
A: Did you get the same thing ?
B: Okay .
D: Yeah .
B: Um .
B: So we're gonna have like individual work and then a meeting about it .
B: And repeat that process three times .
B: Um and at this point we get try out the whiteboard over there .
B: Um .
B: So uh you get to draw your favourite animal and sum up your favourite characteristics of it .
B: So who would like to go first ?
D: I will go .
D: That's fine .
B: Very good .
D: Alright .
D: So This one here , right ?
B: Mm-hmm .
D: Okay .
D: Very nice .
D: Alright .
D: My favourite animal is like A beagle .
D: Um charac favourite characteristics of it ?
D: Is that right ?
B: Yeah .
D: Uh , right , well basically um high priority for any animal for me is that they be willing to take a lot of physical affection from their family .
B: Yeah .
D: And , yeah that they have lots of personality and uh be fit and in robust good health .
D: So this is blue .
D: Blue beagle .
D: My family's beagle .
B: Right .
B: Lovely .
C: Well , my favourite animal would be a monkey .
C: Then they're small cute and furry , and uh when planet of the apes becomes real , I'm gonna be up there with them .
B: Right .
A: Cool .
A: There's too much gear .
B: You can take as long over this as you like , because we haven't got an awful lot to discuss .
B: Ok oh we do we do .
B: Don't feel like you're in a rush , anyway .
A: Okay .
D: I coulda told you a whole lot more about beagles .
B: Ach why not We might have to get you up again then .
D: Boy , let me tell you .
B: I don't know what mine is .
B: I'm gonna have to think on the spot now .
D: Impressionist .
A: Can't draw .
B: Is that a whale ?
A: Um .
A: Yeah .
A: Um , well anyway , I don't know , it's just the first animal I can think off the top of my head .
A: Um .
A: Yes .
A: Big reason is 'cause I'm allergic to most animals .
A: Allergic to animal fur , so um fish was a natural choice .
B: Ah .
A: Um , yeah , and I kind of like whales .
A: They come in and go eat everything in sight .
A: And they're quite harmless and mild and interesting .
D: Alright .
D: Mm .
B: Okay .
B: God , I still don't know what I'm gonna write about .
B: Um .
D: Superb sketch , by the way .
A: Tail's a bit big , I think .
B: I was gonna choose a dog as well .
B: But I'll just draw a different kind of dog .
D: Yep .
B: M my favourite animal is my own dog at home .
B: Um That doesn't really look like him , actually .
B: He looks more like a pig , actually .
B: Ah well .
D: I see a dog in there .
B: Do you ?
D: Yep .
B: Oh that's very good of you .
D: Now I see a rooster .
B: Uh .
D: What kind is it ?
B: Um he's a mixture of uh various things .
B: Um and what do I like about him , um That's just to suggest that his tail wags .
B: Um he's very friendly and cheery and always pleased to see you , and very kind of affectionate and um uh and he's quite quite wee as well so you know he can doesn't take up too much space .
B: Um and uh And he does a funny thing where he chases his tail as well , which is quite amusing , so It is .
D: Is he aware that th it's his own cha tail he's chasing ?
B: I think it is .
B: He only does it after he's had his dinner and um he'll just all of a sudden just get up and start chasing his tail 'round the living room .
D: Hmm .
A: It's an after dinner dog then .
B: Yeah , so uh Yeah , maybe .
D: Probably when he was little he got lots of attention for doing it and has forever been conditioned .
B: Maybe .
B: Right , um where did you find this ?
B: Just down here ?
B: Yeah .
B: Okay .
B: Um what are we doing next ?
B: Uh um .
B: Okay , uh we now need to discuss the project finance .
B: Um so according to the brief um we're gonna be selling this remote control for twenty five Euro , um and we're aiming to make fifty million Euro .
B: Um so we're gonna be selling this on an international scale .
B: And uh we don't want it to cost any more than uh twelve fifty Euros , so fifty percent of the selling price .
D: 'Kay .
D: Um , can we just go over that again ?
B: Sure .
D: Uh , so bas at twel Alright , yeah .
D: Okay .
D: So cost like production cost is twelve fifty , but selling price is is that wholesale or retail ?
B: All together .
D: Like on the shelf .
B: Um I dunno .
B: I imagine That's a good question .
D: Our sale our sale anyway .
B: I imagine it probably is our sale actually because it's probably up to the the um the retailer to uh sell it for whatever price they want .
D: Yeah , okay okay .
D: Okay .
D: Mm-hmm .
B: Um .
D: Alright .
B: But I I don't know , I mean do you think the fact that it's going to be sold internationally will have a bearing on how we design it at all ?
D: Yes .
B: Think it will ?
D: Mm-hmm .
B: Um .
D: Mm-hmm .
B: Hmm .
D: Well right away I'm wondering if there's um th th uh , like with D_V_D_ players , if there are zones .
B: Oh yeah , regions and stuff , yeah .
D: Um f frequencies or something um as well as uh characters , um different uh keypad styles and s symbols .
B: Yeah .
B: Okay .
A: Hmm .
B: Yeah .
B: Well for a remote control , do you think that will be I suppose it's depends on how complicated our remote control is .
D: Um .
D: I don't know .
D: Yeah .
A: It does make sense from maybe the design point of view 'cause you have more complicated characters like European languages , then you need more buttons .
B: Yeah , yeah .
D: Yeah .
A: So , possibly .
D: Yeah .
B: Okay .
D: And then a and then al the other thing international is on top of the price .
D: I'm thinking the price might might appeal to a certain market in one region , whereas in another it'll be different , so Just a chara just a characteristic of the Just Or just like , basic product podi positioning , the twenty five Euro remote control might be a big hit in London , might not be such a big hit in Greece , who knows , something like that , yeah .
B: What , just like in terms of like the wealth of the country ?
B: Like how much money people have to spend on things like ?
B: Aye , I see what you mean , yeah .
B: Marketing .
B: Good marketing thoughts .
D: Yep .
B: Oh gosh , I should be writing all this down .
B: Um .
D: Right away I'm making some kind of assumptions about what what information we're given here , thinking , 'kay trendy probably means something other than just basic , something other than just standard .
B: Mm .
B: Yeah .
D: Um so I'm wondering right away , is selling twenty five Euros , is that sort of the thi is this gonna to be like the premium product kinda thing or Uh-huh .
B: Yeah , yeah .
B: Like how much does , you know , a remote control cost .
B: Well twenty five Euro , I mean that's um that's about like eighteen pounds or something , isn't it ?
D: Mm-hmm .
B: Or no , is it as much as that ?
B: Sixteen seventeen eighteen pounds .
D: Yep .
D: Yeah , I'd say so , yeah .
B: Um , I dunno , I've never bought a remote control , so I don't know how how good a remote control that would get you .
D: No .
D: Yeah , yeah .
B: Um .
B: But yeah , I suppose it has to look kind of cool and gimmicky .
D: Mm-hmm .
B: Um right , okay .
B: Let me just scoot on ahead here .
B: Okay .
B: Um well d Does anybody have anything to add to uh to the finance issue at all ?
D: Do we have any other background information on like how that compares to other other Yeah .
B: Thin No , actually .
B: That would be useful , though , wouldn't it , if you knew like what your money would get you now .
A: Hmm .
D: Mm-hmm .
B: Mm-hmm .
D: Yeah , interesting thing about discussing um production of a remote control for me is that l as you point out , I just don't think of remote controls as somethin something people consciously assess in their purchasing habits .
B: Yeah , yeah .
D: It's just like getting shoelaces with shoes or something .
B: Oh .
D: It just comes along .
B: Five minutes to end of meeting .
B: Oh , okay .
B: We're a bit behind .
D: Do you know what I mean ?
C: Yeah .
D: Like so sort of like how do you I I mean one one way of looking at it would be , well the people producing television sets , maybe they have to buy remote controls .
A: Yeah .
D: Or another way is maybe people who have T_V_ sets are really fed up with their remote control and they really want a better one or something .
C: I know um My parents went out and bought um remote controls because um they got fed up of having four or five different remote controls for each things the house .
D: But Right .
D: Right .
C: So um for them it was just how many devices control .
D: Okay so Right , so in function one of the priorities might be to combine as many uses I think so .
B: Yeah .
B: Right , so do you think that should be like a main design aim of our remote control d you know , do your your satellite and your regular telly and your V_C_R_ and everything ?
D: Yeah , yeah .
D: Yeah .
D: Well like um , maybe what we could use is a sort of like a example of a successful other piece technology is palm palm pilots .
D: They're gone from being just like little sort of scribble boards to cameras , M_P_ three players , telephones , everything , agenda .
B: Mm-hmm .
D: So , like , I wonder if we might add something new to the to the remote control market , such as the lighting in your house , or um Yeah , yeah .
B: Yeah .
B: Or even like , you know , notes about um what you wanna watch .
B: Like you might put in there oh I want to watch such and such and look a Oh that's a good idea .
D: An Yeah .
B: So extra functionalities .
D: Like , p personally for me , at home I've I've combined the um the audio video of my television set and my D_V_D_ player and my C_D_ player .
D: So they w all work actually function together but I have different remote controls for each of them .
B: Mm-hmm .
D: So it's sort of ironic that that then they're in there um you know , the sound and everything it's just one system .
D: But each one's got its own little part .
B: Hmm .
B: Um okay , uh I'd wel we're gonna have to wrap up pretty quickly in the next couple of minutes .
B: Um I'll just check we've nothing else .
B: Okay .
B: Um so anything else anybody wants to add about what they don't like about remote controls they've used , what they would really like to be part of this new one at all ?
A: And you keep losing them .
B: You keep losing them .
D: Mm .
B: Okay .
A: Finding them is really a pain , you know .
D: Mm .
A: I mean it's usually quite small , or when you want it right , it slipped behind the couch or it's kicked under the table .
D: Mm .
D: Mm-hmm .
D: Mm-hmm .
B: Yeah .
D: Yeah .
B: W You get those ones where you can , if you like , whistle or make a really high pitched noise they beep .
D: Yeah .
A: You know .
D: That's just really good id Yep .
B: There I mean is that something we'd want to include , do you think ?
D: Uh , sure .
B: Dunno .
B: Okay maybe .
D: I remember when the first remote control my my family had was on a cable .
D: Actually had a cable between it and the T_V_ and big like buttons that sort of like , like on a blender or something .
B: My goodness .
D: And um , you know , when I think about what they are now , it's better , but actually it's still kind of , I dunno , like a massive junky thing on the table .
B: Still feels quite primitive .
D: Maybe we could think about how , could be more , you know , streamlined .
B: Maybe like a touch screen or something ?
D: S Something like that , yeah .
B: Okay .
D: Or whatever would be technologically reasonable .
B: Uh-huh , okay .
B: Well I guess that's up to our industrial designer .
D: 'Cause it could b it could it could be that f it could be that functionally that doesn't make it any better , but that just the appeal of of not having You know , these days there's a r pe things in people's homes are becoming more and more like chic , you know .
B: It looks better .
B: Yeah .
D: Um , nicer materials and might be be worth exploring anyway .
B: Okay .
B: Okay .
C: Uh .
B: Right , well um so just to wrap up , the next meeting's gonna be in thirty minutes .
B: So that's about um about ten to twelve by my watch .
B: Um so inbetween now and then , um as the industrial designer , you're gonna be working on you know the actual working design of it so y you know what you're doing there .
A: Yep .
B: Um for user interface , technical functions , I guess that's you know like what we've been talking about , what it'll actually do .
B: Um and uh marketing executive , you'll be just thinking about what it actually what , you know , what requirements it has to has to fulfil and you'll all get instructions emailed to you , I guess .
D: Okay .
B: Um .
B: Yeah , so it's th the functional design stage is next , I guess .
B: And uh and that's the end of the meeting .
B: So I got that little message a lot sooner than I thought I would , so Mm-hmm .
D: Um .
D: Before we wrap up , just to make sure we're all on the same page here , um , do we We were given sort of an example of a coffee machine or something , right ?
B: Uh-huh , yeah .
A: Mm-hmm .
D: Well , um are we at ma right now on the assumption that our television remote control may have features which go beyond the television ?
D: Or are we keeping sort of like a a design commitment to television features ?
B: Th Okay , well just very quickly 'cause this we're supposed to finish now .
D: I I don't know .
D: Yep .
B: Um I guess that's up to us , I mean you probably want some kind of unique selling point of it , so um , you know Yeah .
D: Yeah , sure .
D: Okay .
A: I think one factor would be production cost .
D: Okay , yeah .
A: Because there's a cap there , so um depends on how much you can cram into that price .
D: Okay .
B: Mm-hmm .
D: Okay .
A: Um .
B: Yeah .
A: I think that that's the main factor .
B: Okay .
D: Okay .
B: Right , okay , we'll that's that's the end of the meeting , then .
D: Alright .
B: Um .
B: So , uh thank you all for coming .
A: Cool .

In [148]:
df

,Dialogue,Summaries
0,B: Okay .\nB: Right .\nB: Um well this is the ...,The project manager introduced the upcoming pr...
1,B: Is that alright now ?\nB: Okay .\nB: Sorry ...,The project manager briefed the team on some n...
2,A: 'S to do now is to decide how to fulfil wha...,The project manager recapped the decisions mad...
3,B: Okay we all all set ?\nB: Right .\nB: Well ...,The project manager recapped the decisions mad...
4,"C: .\nD: .\nD: .\nB: Okay , well I think we're...",The team members introduced themselves to each...
...,...,...
132,B: .\nD: .\nA: Do you need to change anything ...,"For the conceptual design, the marketing exper..."
133,A: .\nA: .\nA: .\nB: .\nC: .\nD: .\nB: That's ...,The UI and ID presented a prototype drawing of...
134,"A: Okay , good morning .\nA: This is our first...",The goal of the project is to design an origin...
135,D: .\nD: .\nD: .\nD: .\nA: Wait for the market...,Customers are willing to pay more for fancier ...
136,A: .\nA: .\nC: .\nC: .\nC: ?\nC: .\nC: .\nC: ....,The UI and ID presented a prototype drawing of...

In [150]:
df.to_csv('gg.csv', index=False)

In [151]:
d2 = pd.read_csv('gg.csv')

In [154]:
print(d2['Dialogue'][0])

B: Okay .
B: Right .
B: Um well this is the kick-off meeting for our our project .
B: Um and um this is just what we're gonna be doing over the next twenty five minutes .
D: Mm-hmm .
B: Um so first of all , just to kind of make sure that we all know each other , I'm Laura and I'm the project manager .
B: Do you want to introduce yourself again ?
D: Great .
A: Hi , I'm David and I'm supposed to be an industrial designer .
B: Okay .
D: And I'm Andrew and I'm uh our marketing expert .
C: Um I'm Craig and I'm User Interface .
B: Great .
B: Okay .
B: Um so we're designing a new remote control and um Oh I have to record who's here actually .
B: So that's David , Andrew and Craig , isn't it ?
B: And you all arrived on time .
B: Um yeah so des uh design a new remote control .
B: Um , as you can see it's supposed to be original , trendy and user friendly .
B: Um so that's kind of our our brief , as it were .
B: Um and so there are three different stages to the design .
B: Um I'm not really sure what what you guys have already received um in your emails .
B: What did you get ?
A: Um , I just got the project announcement about what the project is .
B: Mm-hmm .
A: Designing a remote control .
D: Mm-hmm .
A: That's about it , didn't get anything else .
D: Mm-hmm .
D: Yeah , that's that's it .
B: Is that what everybody got ?
C: Yeah .
A: Did you get the same thing ?
B: Okay .
D: Yeah .
B: Um .
B: So we're gonna have like individual work and then a meeting about it .
B: And repeat that process three times .
B: Um and at this point we get try out the whiteboard over there .
B: Um .
B: So uh you get to draw your favourite animal and sum up your favourite characteristics of it .
B: So who would like to go first ?
D: I will go .
D: That's fine .
B: Very good .
D: Alright .
D: So This one here , right ?
B: Mm-hmm .
D: Okay .
D: Very nice .
D: Alright .
D: My favourite animal is like A beagle .
D: Um charac favourite characteristics of it ?
D: Is that right ?
B: Yeah .
D: Uh , right , well basically um high priority for any animal for me is that they be willing to take a lot of physical affection from their family .
B: Yeah .
D: And , yeah that they have lots of personality and uh be fit and in robust good health .
D: So this is blue .
D: Blue beagle .
D: My family's beagle .
B: Right .
B: Lovely .
C: Well , my favourite animal would be a monkey .
C: Then they're small cute and furry , and uh when planet of the apes becomes real , I'm gonna be up there with them .
B: Right .
A: Cool .
A: There's too much gear .
B: You can take as long over this as you like , because we haven't got an awful lot to discuss .
B: Ok oh we do we do .
B: Don't feel like you're in a rush , anyway .
A: Okay .
D: I coulda told you a whole lot more about beagles .
B: Ach why not We might have to get you up again then .
D: Boy , let me tell you .
B: I don't know what mine is .
B: I'm gonna have to think on the spot now .
D: Impressionist .
A: Can't draw .
B: Is that a whale ?
A: Um .
A: Yeah .
A: Um , well anyway , I don't know , it's just the first animal I can think off the top of my head .
A: Um .
A: Yes .
A: Big reason is 'cause I'm allergic to most animals .
A: Allergic to animal fur , so um fish was a natural choice .
B: Ah .
A: Um , yeah , and I kind of like whales .
A: They come in and go eat everything in sight .
A: And they're quite harmless and mild and interesting .
D: Alright .
D: Mm .
B: Okay .
B: God , I still don't know what I'm gonna write about .
B: Um .
D: Superb sketch , by the way .
A: Tail's a bit big , I think .
B: I was gonna choose a dog as well .
B: But I'll just draw a different kind of dog .
D: Yep .
B: M my favourite animal is my own dog at home .
B: Um That doesn't really look like him , actually .
B: He looks more like a pig , actually .
B: Ah well .
D: I see a dog in there .
B: Do you ?
D: Yep .
B: Oh that's very good of you .
D: Now I see a rooster .
B: Uh .
D: What kind is it ?
B: Um he's a mixture of uh various things .
B: Um and what do I like about him , um That's just to suggest that his tail wags .
B: Um he's very friendly and cheery and always pleased to see you , and very kind of affectionate and um uh and he's quite quite wee as well so you know he can doesn't take up too much space .
B: Um and uh And he does a funny thing where he chases his tail as well , which is quite amusing , so It is .
D: Is he aware that th it's his own cha tail he's chasing ?
B: I think it is .
B: He only does it after he's had his dinner and um he'll just all of a sudden just get up and start chasing his tail 'round the living room .
D: Hmm .
A: It's an after dinner dog then .
B: Yeah , so uh Yeah , maybe .
D: Probably when he was little he got lots of attention for doing it and has forever been conditioned .
B: Maybe .
B: Right , um where did you find this ?
B: Just down here ?
B: Yeah .
B: Okay .
B: Um what are we doing next ?
B: Uh um .
B: Okay , uh we now need to discuss the project finance .
B: Um so according to the brief um we're gonna be selling this remote control for twenty five Euro , um and we're aiming to make fifty million Euro .
B: Um so we're gonna be selling this on an international scale .
B: And uh we don't want it to cost any more than uh twelve fifty Euros , so fifty percent of the selling price .
D: 'Kay .
D: Um , can we just go over that again ?
B: Sure .
D: Uh , so bas at twel Alright , yeah .
D: Okay .
D: So cost like production cost is twelve fifty , but selling price is is that wholesale or retail ?
B: All together .
D: Like on the shelf .
B: Um I dunno .
B: I imagine That's a good question .
D: Our sale our sale anyway .
B: I imagine it probably is our sale actually because it's probably up to the the um the retailer to uh sell it for whatever price they want .
D: Yeah , okay okay .
D: Okay .
D: Mm-hmm .
B: Um .
D: Alright .
B: But I I don't know , I mean do you think the fact that it's going to be sold internationally will have a bearing on how we design it at all ?
D: Yes .
B: Think it will ?
D: Mm-hmm .
B: Um .
D: Mm-hmm .
B: Hmm .
D: Well right away I'm wondering if there's um th th uh , like with D_V_D_ players , if there are zones .
B: Oh yeah , regions and stuff , yeah .
D: Um f frequencies or something um as well as uh characters , um different uh keypad styles and s symbols .
B: Yeah .
B: Okay .
A: Hmm .
B: Yeah .
B: Well for a remote control , do you think that will be I suppose it's depends on how complicated our remote control is .
D: Um .
D: I don't know .
D: Yeah .
A: It does make sense from maybe the design point of view 'cause you have more complicated characters like European languages , then you need more buttons .
B: Yeah , yeah .
D: Yeah .
A: So , possibly .
D: Yeah .
B: Okay .
D: And then a and then al the other thing international is on top of the price .
D: I'm thinking the price might might appeal to a certain market in one region , whereas in another it'll be different , so Just a chara just a characteristic of the Just Or just like , basic product podi positioning , the twenty five Euro remote control might be a big hit in London , might not be such a big hit in Greece , who knows , something like that , yeah .
B: What , just like in terms of like the wealth of the country ?
B: Like how much money people have to spend on things like ?
B: Aye , I see what you mean , yeah .
B: Marketing .
B: Good marketing thoughts .
D: Yep .
B: Oh gosh , I should be writing all this down .
B: Um .
D: Right away I'm making some kind of assumptions about what what information we're given here , thinking , 'kay trendy probably means something other than just basic , something other than just standard .
B: Mm .
B: Yeah .
D: Um so I'm wondering right away , is selling twenty five Euros , is that sort of the thi is this gonna to be like the premium product kinda thing or Uh-huh .
B: Yeah , yeah .
B: Like how much does , you know , a remote control cost .
B: Well twenty five Euro , I mean that's um that's about like eighteen pounds or something , isn't it ?
D: Mm-hmm .
B: Or no , is it as much as that ?
B: Sixteen seventeen eighteen pounds .
D: Yep .
D: Yeah , I'd say so , yeah .
B: Um , I dunno , I've never bought a remote control , so I don't know how how good a remote control that would get you .
D: No .
D: Yeah , yeah .
B: Um .
B: But yeah , I suppose it has to look kind of cool and gimmicky .
D: Mm-hmm .
B: Um right , okay .
B: Let me just scoot on ahead here .
B: Okay .
B: Um well d Does anybody have anything to add to uh to the finance issue at all ?
D: Do we have any other background information on like how that compares to other other Yeah .
B: Thin No , actually .
B: That would be useful , though , wouldn't it , if you knew like what your money would get you now .
A: Hmm .
D: Mm-hmm .
B: Mm-hmm .
D: Yeah , interesting thing about discussing um production of a remote control for me is that l as you point out , I just don't think of remote controls as somethin something people consciously assess in their purchasing habits .
B: Yeah , yeah .
D: It's just like getting shoelaces with shoes or something .
B: Oh .
D: It just comes along .
B: Five minutes to end of meeting .
B: Oh , okay .
B: We're a bit behind .
D: Do you know what I mean ?
C: Yeah .
D: Like so sort of like how do you I I mean one one way of looking at it would be , well the people producing television sets , maybe they have to buy remote controls .
A: Yeah .
D: Or another way is maybe people who have T_V_ sets are really fed up with their remote control and they really want a better one or something .
C: I know um My parents went out and bought um remote controls because um they got fed up of having four or five different remote controls for each things the house .
D: But Right .
D: Right .
C: So um for them it was just how many devices control .
D: Okay so Right , so in function one of the priorities might be to combine as many uses I think so .
B: Yeah .
B: Right , so do you think that should be like a main design aim of our remote control d you know , do your your satellite and your regular telly and your V_C_R_ and everything ?
D: Yeah , yeah .
D: Yeah .
D: Well like um , maybe what we could use is a sort of like a example of a successful other piece technology is palm palm pilots .
D: They're gone from being just like little sort of scribble boards to cameras , M_P_ three players , telephones , everything , agenda .
B: Mm-hmm .
D: So , like , I wonder if we might add something new to the to the remote control market , such as the lighting in your house , or um Yeah , yeah .
B: Yeah .
B: Or even like , you know , notes about um what you wanna watch .
B: Like you might put in there oh I want to watch such and such and look a Oh that's a good idea .
D: An Yeah .
B: So extra functionalities .
D: Like , p personally for me , at home I've I've combined the um the audio video of my television set and my D_V_D_ player and my C_D_ player .
D: So they w all work actually function together but I have different remote controls for each of them .
B: Mm-hmm .
D: So it's sort of ironic that that then they're in there um you know , the sound and everything it's just one system .
D: But each one's got its own little part .
B: Hmm .
B: Um okay , uh I'd wel we're gonna have to wrap up pretty quickly in the next couple of minutes .
B: Um I'll just check we've nothing else .
B: Okay .
B: Um so anything else anybody wants to add about what they don't like about remote controls they've used , what they would really like to be part of this new one at all ?
A: And you keep losing them .
B: You keep losing them .
D: Mm .
B: Okay .
A: Finding them is really a pain , you know .
D: Mm .
A: I mean it's usually quite small , or when you want it right , it slipped behind the couch or it's kicked under the table .
D: Mm .
D: Mm-hmm .
D: Mm-hmm .
B: Yeah .
D: Yeah .
B: W You get those ones where you can , if you like , whistle or make a really high pitched noise they beep .
D: Yeah .
A: You know .
D: That's just really good id Yep .
B: There I mean is that something we'd want to include , do you think ?
D: Uh , sure .
B: Dunno .
B: Okay maybe .
D: I remember when the first remote control my my family had was on a cable .
D: Actually had a cable between it and the T_V_ and big like buttons that sort of like , like on a blender or something .
B: My goodness .
D: And um , you know , when I think about what they are now , it's better , but actually it's still kind of , I dunno , like a massive junky thing on the table .
B: Still feels quite primitive .
D: Maybe we could think about how , could be more , you know , streamlined .
B: Maybe like a touch screen or something ?
D: S Something like that , yeah .
B: Okay .
D: Or whatever would be technologically reasonable .
B: Uh-huh , okay .
B: Well I guess that's up to our industrial designer .
D: 'Cause it could b it could it could be that f it could be that functionally that doesn't make it any better , but that just the appeal of of not having You know , these days there's a r pe things in people's homes are becoming more and more like chic , you know .
B: It looks better .
B: Yeah .
D: Um , nicer materials and might be be worth exploring anyway .
B: Okay .
B: Okay .
C: Uh .
B: Right , well um so just to wrap up , the next meeting's gonna be in thirty minutes .
B: So that's about um about ten to twelve by my watch .
B: Um so inbetween now and then , um as the industrial designer , you're gonna be working on you know the actual working design of it so y you know what you're doing there .
A: Yep .
B: Um for user interface , technical functions , I guess that's you know like what we've been talking about , what it'll actually do .
B: Um and uh marketing executive , you'll be just thinking about what it actually what , you know , what requirements it has to has to fulfil and you'll all get instructions emailed to you , I guess .
D: Okay .
B: Um .
B: Yeah , so it's th the functional design stage is next , I guess .
B: And uh and that's the end of the meeting .
B: So I got that little message a lot sooner than I thought I would , so Mm-hmm .
D: Um .
D: Before we wrap up , just to make sure we're all on the same page here , um , do we We were given sort of an example of a coffee machine or something , right ?
B: Uh-huh , yeah .
A: Mm-hmm .
D: Well , um are we at ma right now on the assumption that our television remote control may have features which go beyond the television ?
D: Or are we keeping sort of like a a design commitment to television features ?
B: Th Okay , well just very quickly 'cause this we're supposed to finish now .
D: I I don't know .
D: Yep .
B: Um I guess that's up to us , I mean you probably want some kind of unique selling point of it , so um , you know Yeah .
D: Yeah , sure .
D: Okay .
A: I think one factor would be production cost .
D: Okay , yeah .
A: Because there's a cap there , so um depends on how much you can cram into that price .
D: Okay .
B: Mm-hmm .
D: Okay .
A: Um .
B: Yeah .
A: I think that that's the main factor .
B: Okay .
D: Okay .
B: Right , okay , we'll that's that's the end of the meeting , then .
D: Alright .
B: Um .
B: So , uh thank you all for coming .
A: Cool .